document:
  name: Linee guida per l’acquisizione, la circolazione e il riuso delle riproduzioni dei bei culturali in ambiente digitale
  description: |
      Il PND costituisce la visione strategica con la quale il Ministero della Cultura intende promuovere e organizzare il processo di trasformazione digitale nel quinquennio 2022-2026.
      Il piano si rivolge ai musei, agli archivi, alle biblioteche, agli istituti centrali e ai luoghi della cultura statali che conservano, gestiscono e valorizzano i beni culturali.
  tags:
      - patrimonio culturale digitale
      - digitalizzazione
      - digital transformation
      - circolazione e riuso beni culturali
