document:
  name: Linee guida per l’acquisizione, la circolazione e il riuso delle riproduzioni dei beni culturali in ambiente digitale
  description: |
      Le Linee guida 3 chiariscono le norme che disciplinano l’acquisizione, la circolazione e il riuso delle riproduzioni dei beni culturali in ambiente digitale. Questo documento ha l’obiettivo di mettere le istituzioni e gli utenti nelle condizioni di distinguere senza equivoci i limiti e le possibilità di riutilizzo delle riproduzioni rese disponibili in rete dagli istituti.
  tags:
      - patrimonio culturale digitale
      - digitalizzazione
      - digital transformation
      - circolazione e riuso beni culturali
